license_id: cc-by
methodology: "https://images.transparencycdn.org/images/CPI-2024-Methodology.zip"
caveats: None
dataset_source: Transparency International
package_creator: HDX Data Systems Team
private: False
maintainer: "bfeeb369-fb53-4ecd-b8d2-e98b8020a1f9" # hdx_tony_burke
owner_org:  "e0035cc4-87fb-443c-8045-4e9f7463a67c" # transparencyinternational
data_update_frequency: 365
notes: |
  The Corruption Perception Index (CPI) scores and ranks 180 countries and territories worldwide based on how corrupt a country’s public sector is perceived to be by experts and business executives. It is a composite index, a combination of at least 3 and up to 13 surveys and assessments of corruption, collected by a variety of reputable institutions. The results are given on a scale of 0 (highly corrupt) to 100 (very clean). The CPI is the most widely used indicator of corruption worldwide.

  Read more about the CPI here: [https://www.transparency.org/en/cpi](https://www.transparency.org/en/cpi)
